# Generated by Django 5.0.7 on 2024-07-25 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protagonista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'protagonistas',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('Protagonista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='peliculas', to='peliculas.protagonista')),
            ],
            options={
                'db_table': 'peliculas',
            },
        ),
    ]
